"""Where every part of Thor sits, in the design's own frame.

This module defines no node. It holds the numbers the machine is built
from, and it is imported directly (never through the package) by every
sub-assembly, so the framework's import walk invalidates exactly the nodes
that read an edited number.

The machine frame is the FreeCAD assembly's own: **Z up, origin on the
mounting face of BaseBot**, X toward the electronics box's open side, Y
completing the right-handed set. At the home pose the arm stands fully
extended along +Z with the tool pointing up.

`LINKS` is transcribed from the design's own FreeCAD Assembly4 documents,
which store each link's solved global placement. It is generated by
``python -m simulation.tools.emit_layout`` and checked, entry for entry,
against a fresh read of those documents by ``simulation/test_layout.py``.
Every translation is in millimetres, every angle in degrees, and every
rotation is stated as one axis and one angle applied before the
translation — the order ``node.rotate(angle, axis)`` then
``node.translate(t)`` reproduces.
"""

from collections import namedtuple

#: A part instance: the label the design gives it, the FreeCAD source
#: document it comes from (``None`` for a bought component), the label of
#: the in-document component it is an instance of (``None`` for a printed
#: part), and its placement.
Placed = namedtuple('Placed', 'label source component translate axis angle')

#: Two coincident faces cannot be asked whether they touch, so every
#: seated part stands this far off its seat along the seat normal.
SEAT_GAP = 0.05

# --- the joints -----------------------------------------------------------
#
# Measured from the placements below: the shoulder is the Art2 link's own
# origin, the elbow is Art3Pulley's axis carried through the Art3 link, and
# the wrist is the Art56 link's own origin.

#: Height of the shoulder axis above the mounting face, mm.
SHOULDER_Z = 202.0
#: Height of the elbow axis, mm. SHOULDER_Z + 160.0, the author's own span.
ELBOW_Z = 362.0
#: Height of the wrist axis, mm. The author's drawing says 195.00 above the
#: elbow; the assembly puts it 194.0 above. See design.md, Finding 1.
WRIST_Z = 556.0

# --- the gear pairs -------------------------------------------------------
#
# The design's assembly leaves every printed gear pair interpenetrating: it
# never put a pinion on its shaft at an angle that meshes. A builder does,
# so the model does too, and each phase below is measured rather than
# chosen: the pinion is swept through one tooth pitch against its mate by
# `simulation.tools.geometry.mesh_window`, and it is put on at the centre of
# the window where the pair shares least.
#
# Two of the five pairs never reach zero however they are phased, because
# something other than a tooth fouls: those floors are recorded here and
# again in `simulation.seats`, and they are findings about the design, not
# tolerances the model grants itself.

#: (mate, teeth on the driver, teeth on the mate, phase, window width,
#: floor volume) per gear pair, keyed by the design's own label for the
#: driver. Angles in degrees, volume in cubic millimetres.
Mesh = namedtuple('Mesh', 'mate driver_teeth mate_teeth phase width floor')

MESH = {
    'Art1GearMotor_Art1GearMotor':
        Mesh('Art1Bot_Art1Bot', 10, 50, 23.4, 0.05, 0.1965),
    'Art2MotorGear_Art2MotorGear':
        Mesh('Art2BodyA_Art2BodyA', 10, 60, 31.5, 5.0, 0.0),
    'Art2MotorGear_Art2MotorGear001':
        Mesh('Art2BodyA_Art2BodyA', 10, 60, 19.5, 5.0, 0.0),
    'Art4MotorGear_Art4MotorGear':
        Mesh('Art4TransmissionColumn_Art4TransmissionColumn',
             10, 20, 31.0, 4.0, 24.2991),
    'Art56SmallGear_Art56SmallGear':
        Mesh('Art56GearPlate_Art56GearPlate', 15, 30, 0.4, 0.4, 0.0),
    'Art56SmallGear_Art56SmallGear001':
        Mesh('Art56GearPlate_Art56GearPlate', 15, 30, 23.4, 0.4, 0.0),
}


#: What the author's dimension drawing states, for the contract that
#: compares the two.
DRAWN_BASE_TO_SHOULDER = 202.00
DRAWN_SHOULDER_TO_ELBOW = 160.00
DRAWN_ELBOW_TO_WRIST = 195.00
DRAWN_WRIST_TO_TOOL = 67.15

LINKS = {
    'root': (
        Placed('AssemblyBase', 'AssemblyBase.FCStd', None, (0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 0.0),
        Placed('AssemblyArt1', 'AssemblyArt1.FCStd', None, (0.0, 0.0, 79.0), (0.0, 0.0, 1.0), 0.0),
        Placed('AssemblyArt2', 'AssemblyArt2.FCStd', None, (0.0, -68.0, 202.0), (0.0, 0.7071, 0.7071), 180.0),
        Placed('AssemblyArt3', 'AssemblyArt3.FCStd', None, (0.0, 0.0, 443.5), (0.0, 1.0, 0.0), 180.0),
        Placed('AssemblyArt4', 'AssemblyArt4.FCStd', None, (0.0, 0.0, 444.5), (0.0, 0.0, 1.0), 0.0),
        Placed('AssemblyArt56', 'AssemblyArt56.FCStd', None, (0.0, 0.0, 556.0), (0.0, 0.0, 1.0), 90.0),
    ),
    'AssemblyBase': (
        Placed('BaseBot_BaseBot', 'BaseBot.FCStd', None, (0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 0.0),
        Placed('BaseTop_BaseTop', 'BaseTop.FCStd', None, (0.0, 0.0, 65.5), (0.0, 0.0, 1.0), 60.0),
        Placed('BaseBearingFix_BaseBearingFix', 'BaseBearingFix.FCStd', None, (0.0, 0.0, 93.0), (0.0, 0.0, -1.0), 120.0),
        Placed('BaseBoxBody_BaseBoxBody', 'BaseBoxBody.FCStd', None, (0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 180.0),
        Placed('BaseBoxCover_BaseBoxCover', 'BaseBoxCover.FCStd', None, (0.0, 0.0, 65.5), (0.0, 0.0, 1.0), 180.0),
        Placed('Stepper_Nema17x40001', None, 'Stepper_Nema17x40', (40.0, 0.0, 5.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art1GearMotor_Art1GearMotor', 'Art1GearMotor.FCStd', None, (40.0, 0.0, 59.0), (0.0, 0.0, 1.0), 180.0),
        Placed('OpticSensor001', None, 'OpticSensor', (-2.2, 51.0, 45.0), (0.0, 0.0, 1.0), 90.0),
        Placed('Fan_40x40001', None, 'Fan_40x40', (42.5, -36.0, 26.0), (0.0, 0.7071, 0.7071), 180.0),
        Placed('OnOffButton001', None, 'OnOffButton', (-74.4, 67.5, 70.5), (0.0, 0.0, -1.0), 90.0),
        Placed('ResetButton001', None, 'ResetButton', (-74.4, -67.5, 70.5), (0.5774, -0.5774, -0.5774), 120.0),
        Placed('Fan_50x50001', None, 'Fan_50x50', (-127.9, 75.0, 30.0), (0.0, 0.7071, 0.7071), 180.0),
        Placed('Fan_50x50002', None, 'Fan_50x50', (-182.9, 75.0, 30.0), (-1.0, 0.0, 0.0), 90.0),
        Placed('Fan_50x50003', None, 'Fan_50x50', (-127.9, -75.0, 30.0), (1.0, 0.0, 0.0), 90.0),
        Placed('Fan_50x50004', None, 'Fan_50x50', (-182.9, -75.0, 30.0), (1.0, 0.0, 0.0), 90.0),
        Placed('ArduinoMega001', None, 'ArduinoMega', (-160.0, -0.0012, 10.0), (0.0, 0.0, 1.0), 0.0022),
        Placed('JackDC001', None, 'JackDC', (-219.4, -46.5, 17.0), (0.5774, -0.5774, 0.5774), 120.0),
        Placed('NutButton001', None, 'NutButton', (-74.4, 67.5, 64.0), (0.0, 0.0, 1.0), 180.0),
        Placed('NutButton002', None, 'NutButton', (-74.4, -67.5, 64.0), (0.0, 0.0, 1.0), 180.0),
        Placed('Bearing_16014zz001', None, 'Bearing_16014zz', (0.0, 0.0, 92.0), (0.9659, -0.2588, 0.0), 180.0),
    ),
    'AssemblyArt1': (
        Placed('Art1Bot_Art1Bot', 'Art1Bot.fcstd', None, (0.0, 0.0, -30.0), (0.0, 0.0, 1.0), 150.0),
        Placed('Art1Top_Art1Top', 'Art1Top.FCStd', None, (-0.0004, 0.0003, 7.0), (0.0, 0.0, -1.0), 90.0),
        Placed('Art1FanHolder_Art1FanHolder', 'Art1FanHolder.FCStd', None, (40.869, 0.0003, 37.8693), (-0.3574, -0.3574, 0.8629), 98.4211),
        Placed('Art1FanHolder_Art1FanHolder001', 'Art1FanHolder.FCStd', None, (-40.8697, 0.0003, 37.8693), (-0.3574, 0.3574, -0.8629), 98.421),
        Placed('Art1Body_Art1Body', 'Art1Body.fcstd', None, (-0.0004, 0.0003, 25.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art23Optodisk_Art23Optodisk', 'Art23Optodisk.FCStd', None, (-0.0004, 35.0003, 123.0), (-1.0, 0.0, 0.0), 90.0),
        Placed('Bearing_625ZZ001', None, 'Bearing_625ZZ', (-0.0004, 32.0003, 123.0), (-1.0, 0.0, 0.0), 90.0),
        Placed('CommonBearingFixThrough_CommonBearingFixThrough', 'CommonBearingFixThrough.FCStd', None, (-0.0004, 37.0003, 123.0), (-0.5774, -0.5774, -0.5774), 120.0),
        Placed('Nema17_GearBox001', None, 'Nema17_GearBox', (21.4996, 29.0503, 79.7), (0.5774, -0.5774, 0.5774), 120.0),
        Placed('Nema17_GearBox002', None, 'Nema17_GearBox', (-21.5004, 29.0503, 79.7), (0.5774, -0.5774, 0.5774), 120.0),
        Placed('Nema17_GearBox003', None, 'Nema17_GearBox', (-0.0004, 29.0503, 123.0), (0.5774, -0.5774, 0.5774), 120.0),
        Placed('Art2MotorGear_Art2MotorGear', 'Art2MotorGear.FCStd', None, (-21.5003, -45.2497, 79.7), (0.5182, 0.6048, -0.6048), 125.2129),
        Placed('Art2MotorGear_Art2MotorGear001', 'Art2MotorGear.FCStd', None, (21.4997, -45.2497, 79.7), (0.5182, 0.6048, -0.6048), 125.2129),
        Placed('Fan_40x40001', None, 'Fan_40x40', (-38.7484, 0.0003, 39.9907), (-0.3574, 0.3574, -0.8629), 98.421),
        Placed('Fan_40x40002', None, 'Fan_40x40', (38.7477, 0.0003, 39.9907), (-0.3574, -0.3574, 0.8629), 98.4211),
        Placed('Art2BodyACover1_Art2BodyACover1', 'Art2BodyACover1.FCStd', None, (-0.0003, -34.9997, 123.0), (1.0, 0.0, 0.0), 90.0),
        Placed('Pulley_GT2x20_Modified001', None, 'Pulley_GT2x20_Modified', (-0.0003, -56.3497, 123.0), (-0.0012, 0.7071, 0.7071), 179.8659),
        Placed('5x14.5mm001', None, '5x14.5mm', (-0.0003, -49.2497, 123.0), (0.5761, -0.578, 0.578), 120.1096),
        Placed('5x32mm001', None, '5x32mm', (-0.0004, 32.0003, 123.0), (-1.0, 0.0, 0.0), 90.0),
    ),
    'AssemblyArt2': (
        Placed('Art2BodyA_Art2BodyA', 'Art2BodyA.FCStd', None, (0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art2BodyAWindow_Art2BodyAWindow', 'Art2BodyAWindow.FCStd', None, (0.0, 160.0, 0.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art2BodyACover2_Art2BodyACover2', 'Art2BodyACover2.FCStd', None, (0.0, 0.0, 32.0), (0.0, 1.0, 0.0), 180.0),
        Placed('Art2BodyUnion_Art2BodyUnion', 'Art2BodyUnion.FCStd', None, (0.0, 80.0, 68.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art2BodyBCover_Art2BodyBCover', 'Art2BodyBCover.FCStd', None, (0.0, 0.0, 104.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art2BodyB_Art2BodyB', 'Art2BodyB.FCStd', None, (0.0, 0.0, 136.0), (0.0, 1.0, 0.0), 180.0),
        Placed('CommonBearingFix_CommonBearingFix', 'CommonBearingFix.FCStd', None, (0.0, 160.0, 132.0), (0.0, 0.0, 1.0), 0.0),
        Placed('CommonBearingFix_CommonBearingFix001', 'CommonBearingFix.FCStd', None, (0.0, 0.0, 132.0), (0.0, 0.0, 1.0), 0.0),
        Placed('CommonBearingFix_CommonBearingFix002', 'CommonBearingFix.FCStd', None, (0.0, 0.0, 4.0), (0.0, 1.0, 0.0), 180.0),
        Placed('CommonBearingFix_CommonBearingFix003', 'CommonBearingFix.FCStd', None, (0.0, 160.0, 4.0), (0.0, 1.0, 0.0), 180.0),
        Placed('Art2SideCover_Art2SideCover', 'Art2SideCover.FCStd', None, (0.0, 0.0, -2.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art2SideCover_Art2SideCover001', 'Art2SideCover.FCStd', None, (0.0, 0.0, 138.0), (0.0, 1.0, 0.0), 180.0),
        Placed('Art3TensionerBody_Art3TensionerBody', 'Art3TensionerBody.FCStd', None, (10.5, 99.85, 5.0), (0.0, 0.0, 1.0), 90.0),
        Placed('Art3TensionerBody_Art3TensionerBody001', 'Art3TensionerBody.FCStd', None, (-10.5, 99.85, 5.0), (0.0, 0.0, -1.0), 90.0),
        Placed('Art3TensionerPulley_Art3TensionerPulley', 'Art3TensionerPulley.FCStd', None, (14.5, 99.85, 16.0), (0.0, 0.0, 1.0), 90.0),
        Placed('Art3TensionerPulley_Art3TensionerPulley001', 'Art3TensionerPulley.FCStd', None, (-14.5, 99.85, 16.0), (0.0, 0.0, -1.0), 90.0),
        Placed('Bearing_625ZZ001', None, 'Bearing_625ZZ', (0.0, 160.0, 127.0), (0.0, 0.0, 1.0), 90.0),
        Placed('Bearing_625ZZ002', None, 'Bearing_625ZZ', (0.0, 0.0, 127.0), (0.0, 0.0, 1.0), 90.0),
        Placed('Bearing_625ZZ003', None, 'Bearing_625ZZ', (0.0, 0.0, 9.0), (0.7071, 0.7071, 0.0), 180.0),
        Placed('Bearing_625ZZ004', None, 'Bearing_625ZZ', (0.0, 160.0, 9.0), (0.7071, -0.7071, 0.0), 180.0),
        Placed('OpticSensor001', None, 'OpticSensor', (2.2, -31.4, 122.0), (0.7071, -0.7071, 0.0), 180.0),
        Placed('OpticSensor002', None, 'OpticSensor', (-2.2, 191.4, 122.0), (0.7071, 0.7071, 0.0), 180.0),
        Placed('4x14mm001', None, '4x14mm', (14.5, 99.85, 10.5), (0.0, 0.0, 1.0), 0.0),
        Placed('4x14mm002', None, '4x14mm', (-14.5, 99.85, 10.5), (0.0, 0.0, 1.0), 180.0),
        Placed('Bearing_MF84ZZ001', None, 'Bearing_MF84ZZ', (14.5, 99.85, 16.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Bearing_MF84ZZ002', None, 'Bearing_MF84ZZ', (-14.5, 99.85, 16.0), (0.0, 0.0, 1.0), 180.0),
        Placed('Magnet001', None, 'Magnet', (0.0, -54.5, 1.1), (0.7071, -0.7071, 0.0), 180.0),
        Placed('Magnet002', None, 'Magnet', (0.0, 80.0, 1.1), (0.7071, -0.7071, 0.0), 180.0),
        Placed('Magnet003', None, 'Magnet', (0.0, 214.5, 1.1), (0.7071, -0.7071, 0.0), 180.0),
        Placed('Magnet004', None, 'Magnet', (0.0, -54.5, 134.9), (0.0, 0.0, -1.0), 90.0),
        Placed('Magnet005', None, 'Magnet', (0.0, 80.0, 134.9), (0.0, 0.0, -1.0), 90.0),
        Placed('Magnet006', None, 'Magnet', (0.0, 214.5, 134.9), (0.0, 0.0, -1.0), 90.0),
        Placed('Magnet007', None, 'Magnet', (0.0, -54.5, -1.1), (0.0, 0.0, 1.0), 90.0),
        Placed('Magnet008', None, 'Magnet', (0.0, 80.0, -1.1), (0.0, 0.0, 1.0), 90.0),
        Placed('Magnet009', None, 'Magnet', (0.0, 214.5, -1.1), (0.0, 0.0, 1.0), 90.0),
        Placed('Magnet010', None, 'Magnet', (0.0, 214.5, 137.1), (0.7071, 0.7071, 0.0), 180.0),
        Placed('Magnet011', None, 'Magnet', (0.0, 80.0, 137.1), (0.7071, 0.7071, 0.0), 180.0),
        Placed('Magnet012', None, 'Magnet', (0.0, -54.5, 137.1), (0.7071, 0.7071, 0.0), 180.0),
        Placed('5x128mm001', None, '5x128mm', (0.0, 160.0, 4.0), (0.0, 0.0, -1.0), 90.0),
        Placed('GT2_Belt_Art3001', None, 'GT2_Belt_Art3', (0.0, -201.0, 23.0), (0.0, 0.7071, 0.7071), 180.0),
    ),
    'AssemblyArt3': (
        Placed('Art3Body_Art3Body', 'Art3Body.FCStd', None, (0.0, 0.0, -7.0), (0.0, 0.0, 1.0), 0.0),
        Placed('Art23Optodisk_Art23Optodisk', 'Art23Optodisk.FCStd', None, (0.0, 35.0, 81.5), (-1.0, 0.0, 0.0), 90.0),
        Placed('Art3Pulley_Art3Pulley', 'Art3Pulley.FCStd', None, (0.0, -53.0, 81.5), (-1.0, 0.0, 0.0), 90.0),
        Placed('Art4MotorFix_Art4MotorFix', 'Art4MotorFix.FCStd', None, (27.85, 0.0, 82.6), (0.0, 1.0, 0.0), 180.0),
        Placed('Stepper_Nema17x34001', None, 'Stepper_Nema17x34', (27.85, 0.0, 116.6), (0.0, 1.0, 0.0), 180.0),
        Placed('Art4MotorGear_Art4MotorGear', 'Art4MotorGear.FCStd', None, (27.85, 0.0, 66.6), (0.0, 1.0, 0.0), 180.0),
        Placed('Fan_40x40001', None, 'Fan_40x40', (-46.0, 0.0, 99.0), (-0.5774, 0.5774, -0.5774), 120.0),
        Placed('Bearing_625ZZ001', None, 'Bearing_625ZZ', (0.0, 32.0, 81.5), (-0.5774, -0.5774, -0.5774), 120.0),
        Placed('Bearing_625ZZ002', None, 'Bearing_625ZZ', (0.0, -44.0, 81.5), (0.5774, 0.5774, -0.5774), 120.0),
        Placed('CommonBearingFixThrough_CommonBearingFixThrough', 'CommonBearingFixThrough.FCStd', None, (0.0, -49.0, 81.5), (1.0, 0.0, 0.0), 90.0),
        Placed('CommonBearingFixThrough_CommonBearingFixThrough001', 'CommonBearingFixThrough.FCStd', None, (0.0, 37.0, 81.5), (-0.5774, -0.5774, -0.5774), 120.0),
        Placed('OpticSensor001', None, 'OpticSensor', (-32.4, 0.0, 23.5), (0.0, 1.0, 0.0), 180.0),
        Placed('Art4BearingRing_Art4BearingRing', 'Art4BearingRing.FCStd', None, (0.0, 0.0, 4.0), (0.7071, -0.7071, 0.0), 180.0),
        Placed('BearingBalls001', None, 'BearingBalls', (0.0, 0.0, -1.0), (0.7071, -0.7071, 0.0), 180.0),
    ),
    'AssemblyArt4': (
        Placed('Art4TransmissionColumn_Art4TransmissionColumn', 'Art4TransmissionColumn.FCStd', None, (0.0, 0.0, -69.0), (0.0, 0.0, 1.0), 45.0),
        Placed('Art4BodyBot_Art4BodyBot', 'Art4BodyBot.FCStd', None, (0.0, 0.0, 7.0), (0.0, 0.0, -1.0), 90.0),
        Placed('Art4Body_Art4Body', 'Art4Body.FCStd', None, (0.0, 0.0, 11.5), (0.0, 0.0, -1.0), 90.0),
        Placed('Art4BodyFan_Art4BodyFan', 'Art4BodyFan.FCStd', None, (0.0, -66.0, 11.5), (0.0, 0.0, 1.0), 90.0),
        Placed('Art4BodyFan_Art4BodyFan001', 'Art4BodyFan.FCStd', None, (0.0, 66.0, 11.5), (0.0, 0.0, -1.0), 90.0),
        Placed('Art56MotorHolderA_Art56MotorHolderA', 'Art56MotorHolderA.FCStd', None, (24.0, -10.3, 33.6), (0.0, 0.7071, -0.7071), 180.0),
        Placed('Art56MotorHolderA_Art56MotorHolderA001', 'Art56MotorHolderA.FCStd', None, (-24.0, 10.3, 33.6), (-1.0, 0.0, 0.0), 90.0),
        Placed('Stepper_Nema17x34001', None, 'Stepper_Nema17x34', (-24.0, -23.7, 33.6), (-1.0, 0.0, 0.0), 90.0),
        Placed('Stepper_Nema17x34002', None, 'Stepper_Nema17x34', (24.0, 23.7, 33.6), (0.0, 0.7071, -0.7071), 180.0),
        Placed('Art56MotorHolderB_Art56MotorHolderB', 'Art56MotorHolderB.FCStd', None, (24.0, 23.7, 33.6), (0.0, 0.7071, 0.7071), 180.0),
        Placed('Art56MotorHolderB_Art56MotorHolderB001', 'Art56MotorHolderB.FCStd', None, (-24.0, -23.7, 33.6), (1.0, 0.0, 0.0), 90.0),
        Placed('Pulley_GT2x20001', None, 'Pulley_GT2x20', (24.0, -27.9, 33.6), (-1.0, 0.0011, 0.0011), 90.0001),
        Placed('Pulley_GT2x20002', None, 'Pulley_GT2x20', (-24.0, 27.9, 33.6), (0.0131, 0.707, -0.707), 178.4938),
        Placed('Bearing_625ZZ001', None, 'Bearing_625ZZ', (0.0, 46.0, 111.5), (-1.0, 0.0, 0.0), 90.0),
        Placed('Bearing_625ZZ002', None, 'Bearing_625ZZ', (0.0, -46.0, 111.5), (1.0, 0.0, 0.0), 90.0),
        Placed('Fan_40x40001', None, 'Fan_40x40', (0.0, -55.0, 36.5), (0.0, 0.7071, -0.7071), 180.0),
        Placed('Fan_40x40002', None, 'Fan_40x40', (0.0, 55.0, 36.5), (-1.0, 0.0, 0.0), 90.0),
        Placed('Art4BearingFix_Art4BearingFix', 'Art4BearingFix.FCStd', None, (0.0, 51.0, 111.5), (0.0, 0.7071, 0.7071), 180.0),
        Placed('Art4BearingFix_Art4BearingFix001', 'Art4BearingFix.FCStd', None, (0.0, -51.0, 111.5), (1.0, 0.0, 0.0), 90.0),
        Placed('Belt_GT2-208mm001', None, 'Belt_GT2-208mm', (24.0, -20.5, 33.6), (0.0, 1.0, 0.0), 0.1301),
        Placed('Belt_GT2-208mm002', None, 'Belt_GT2-208mm', (-24.0, 20.5, 33.6), (-0.0186, 0.0, 0.9998), 180.0),
        Placed('Shaft_5x102mm001', None, 'Shaft_5x102mm', (0.0, 51.0, 111.5), (1.0, 0.0, 0.0), 90.0),
        Placed('Art4Optodisk_Art4Optodisk', 'Art4Optodisk.FCStd', None, (0.0, 0.0, -5.0), (1.0, 0.0, 0.0), 180.0),
        Placed('MicroEndstop001', None, 'MicroEndstop', (52.25, -6.3, 90.2), (0.0, 0.0, 1.0), 90.0),
        Placed('M8Connector001', None, 'M8Connector', (45.7497, 0.0, 66.5), (0.0, -0.7071, 0.7071), 180.0),
    ),
    'AssemblyArt56': (
        Placed('Art56MotorCoverRing_Art56MotorCoverRing', 'Art56MotorCoverRing.FCStd', None, (0.0, 0.0, 0.0), (-0.5774, 0.5774, -0.5774), 120.0),
        Placed('CommonBearingFixThrough_CommonBearingFixThrough', 'CommonBearingFixThrough.FCStd', None, (-3.0, 0.0, 0.0), (-0.5774, -0.5774, 0.5774), 120.0),
        Placed('Art56GearPlate_Art56GearPlate', 'Art56GearPlate.FCStd', None, (0.0, 0.0, 21.5), (0.866, -0.5, 0.0), 180.0),
        Placed('Art56SmallGear_Art56SmallGear', 'Art56SmallGear.FCStd', None, (-39.4, 0.0001, 0.0), (-0.6163, 0.4902, -0.6163), 127.7687),
        Placed('Art56SmallGear_Art56SmallGear001', 'Art56SmallGear.FCStd', None, (39.4, 0.0001, 0.0), (0.5774, -0.5774, -0.5774), 120.0),
        Placed('Bearing_625ZZ001', None, 'Bearing_625ZZ', (0.0, 0.0, 21.5), (0.0, 0.0, -1.0), 60.0),
        Placed('Bearing_625ZZ002', None, 'Bearing_625ZZ', (2.0, 0.0, 0.0), (-0.6851, -0.2475, 0.6851), 152.1937),
        Placed('GripperBot_GripperBot', 'GripperBot.FCStd', None, (0.0467, -17.1499, 56.5), (0.001, -0.7071, -0.7071), 179.8898),
        Placed('Unnamed_GripperTop', 'GripperTop.FCStd', None, (-0.0072, 2.65, 56.5), (0.001, -0.7071, -0.7071), 179.8898),
        Placed('Servomotor002', None, 'Servomotor', (45.5361, -7.6761, 85.0), (-0.5768, -0.5784, -0.5768), 119.91),
        Placed('ServomotorWheelHorn001', None, 'ServomotorWheelHorn', (14.5154, -0.1105, 89.0), (0.0008, 0.7071, -0.7071), 179.692),
        Placed('GripperActiveArm_GripperActiveArm', 'GripperActiveArm.FCStd', None, (14.5216, -2.4105, 89.0), (-1.0, -0.0038, -0.0011), 90.0001),
        Placed('Unnamed3_GripperPassiveArm', 'GripperPassiveArm.FCStd', None, (-14.4927, -2.6894, 89.0), (-0.0426, 0.7064, 0.7065), 175.3386),
        Placed('Unnamed2_GripperArm', 'GripperArm.FCStd', None, (-5.9928, -2.6663, 107.5), (-0.5779, 0.5763, 0.5779), 120.0901),
        Placed('Unnamed2_GripperArm001', 'GripperArm.FCStd', None, (6.0072, -2.6337, 107.5), (-0.5768, -0.5784, -0.5768), 119.91),
        Placed('Unnamed1_GripperFinger', 'GripperFinger.FCStd', None, (53.5208, -7.5794, 85.0), (0.001, -0.7071, -0.7071), 179.8898),
        Placed('GripperFinger_sym001', None, 'GripperFinger_sym', (-53.4788, -7.8706, 85.0), (0.001, -0.7071, -0.7071), 179.8898),
        Placed('Collar5mm001', None, 'Collar5mm', (-40.4, 0.0001, 0.0), (0.5285, -0.6644, -0.5285), 112.8006),
        Placed('Collar5mm002', None, 'Collar5mm', (40.4, 0.0001, 0.0), (-0.5774, 0.5774, -0.5774), 120.0),
        Placed('GT2x40PulleyM005', None, 'GT2x40PulleyM4', (-18.0, 0.0, 0.0), (-0.5634, -0.6042, 0.5634), 117.7181),
        Placed('GT2x40PulleyM006', None, 'GT2x40PulleyM4', (18.0, 0.0, 0.0), (0.5112, 0.6909, 0.5112), 110.7208),
    ),
}


def links(group):
    """The placed instances of one sub-assembly, or of the root."""
    return LINKS[group]


def link(group, label):
    """One placed instance by the label the design gives it."""
    for placed in LINKS[group]:
        if placed.label == label:
            return placed
    raise KeyError('%s has no instance labelled %r' % (group, label))


def printed(group):
    """The instances of `group` that come from a published printed part."""
    return tuple(p for p in LINKS[group] if p.source is not None)


def bought(group):
    """The instances of `group` the design places but does not publish."""
    return tuple(p for p in LINKS[group] if p.source is None)


def components(group, *names):
    """The bought instances of `group` of the named component kinds."""
    wanted = frozenset(names)
    return tuple(p for p in LINKS[group] if p.component in wanted)


def part_name(placed):
    """The printed part a placed instance is an instance of."""
    if placed.source is None:
        raise ValueError('%r is a bought component, not a printed part'
                         % (placed.label,))
    return placed.source.split('.')[0]
